### ISSUE TITLE
Missing value in business_ethics.csv

### ISSUE THREAD

**Issue by shimatar0** [nlp-waseda/JMMLU#1]
Hi! Thank you for publishing these great benchmarks.

I noticed missing values in the`business_ethics.csv` while using this benchmark.

https://github.com/nlp-waseda/JMMLU/blob/main/JMMLU/business_ethics.csv#L86

You might want to fill in the correct value :)

**Comment by ZeekYin** [comment]
Thank you. I will fix it.
