### ISSUE TITLE
huggingface/datasets support?

### ISSUE THREAD

**Issue by ryokan0123** [nlp-waseda/JMMLU#2]
Hi, thank you for creating and sharing this fantastic repository.

Do you have any plans to make the dataset available on [Hugging Face Hub](https://huggingface.co/datasets)?
I believe it would significantly enhance the dataset's usability.

If not, I am planning to write a data fetching/processing script and put it on the Hub from my account.
Or if you would like to put it from your account, I can help with the process by providing the draft of the script.

Thank you!

**Comment by ZeekYin** [comment]
Thank you. We will upload this under https://huggingface.co/nlp-waseda.

**Comment by ryokan0123** [comment]
Great to hear that.  I'll wait the release!

**Comment by ZeekYin** [comment]
Uploaded. You can find it under https://huggingface.co/nlp-waseda.
