### ISSUE TITLE
医学用語の修正について

### ISSUE THREAD

**Issue by hiroyaiizuka** [nlp-waseda/JMMLU#3]
初めまして、医師の飯塚浩也と申します。
この度は、MMLUを日本語翻訳化してくださり、誠にありがとうございます。

問題を眺めていたところ、気になった点がございましたので、ご報告させてください。

https://github.com/nlp-waseda/JMMLU/blob/main/JMMLU/clinical_knowledge.csv

こちらの65問、`低ボラ性ショック`ですが、こちらは医学用語として正しくありません。

元のMMLU repositoryを確認しましたが、typoのようでした。
<img width="473" alt="CleanShot 2024-02-18 at 05 48 37" src="https://github.com/nlp-waseda/JMMLU/assets/39001773/4010fa8c-58bd-4546-bdf1-ff19df62797b">

hypovolaemic shockですが、正しくは `hypovolemic shock`です。
循環血液量減少性ショック、が正しい日本語翻訳となります。

ご検討のほど、よろしくお願いいたします。

(医学用語ではないのですが、high_school_mathematics.csvの7問目、`雨と晴れ両方の確立は何％か` 確率が確立となっておりますので、こちらもお手隙の時に修正をご検討ください。)

**Comment by ZeekYin** [comment]
貴重なご意見をいただき、誠にありがとうございます。修正をさせていただきます。
