### ISSUE TITLE
医学用語: カテーテルについてのご提案

### ISSUE THREAD

**Issue by hiroyaiizuka** [nlp-waseda/JMMLU#4]
医師の飯塚です。
先日は、ご対応いただきありがとうございました。

本日は、`clinical_knowledge.csv`内での「カテーテル」という命名の使用について、ご相談をさせてください。

```
80問: カテーテル挿入前に行わないことはどれか？ 
(原文: Which of the following would not be done before catheterizing?)
　A: 患者の同意を得る。
　B: 患者を洗浄する。
　C: 有効期限を確認する。
　D: 患者の近親者に連絡する。
　
(正解: D)
```

```
88問: カテーテルの詰まりを除去しようとしても抵抗され、除去できない場合はどうすればよいか？
(原文: If a catheter resists all attempts to unblock it and you are unable to remove it, what should you do?)
　A: より強くカテーテルを抜去する。
　B: 閉塞を解除するためにさらに努力する。
　C: 次回まで放置する。
　D: 医師に助けを求める。
　
(正解: D)
```

医療の世界で、カテーテルという単語には大きく2つの意味で使われます。
・尿道カテーテル
・冠動脈カテーテル

上の問題では、尿道カテーテルの意味合いで使われていると推測されます。
しかし、冠動脈という文脈の場合、80問の正解に影響がおきます。(近親者に説明することもあり、手首からのカテーテル検査では、洗浄をしないため、Bが正解になります。)

そのため、ハルシネーションの原因になるかと思われ、`カテーテル`-> `尿道カテーテル`との明記がより良い可能性が考えられました。このことは、MMLUのGitHubにも報告をさせていただきます。

ご検討のほど、何卒よろしくお願いいたします。

**Comment by ZeekYin** [comment]
ありがとうございます。修正させていただきます。
