### ISSUE TITLE
Error in japanese_geography

### ISSUE THREAD

**Issue by tomohideshibata** [nlp-waseda/JMMLU#5]
Thank you for publishing the great benchmark.

The answer to the following question "日本の都道府県の数はいくつか？" is "A: 45", but I think the correct answer should be "B: 47".
https://github.com/nlp-waseda/JMMLU/blob/main/JMMLU_NC_ND/japanese_geography.csv#L63

Thank you.

**Comment by ZeekYin** [comment]
Thank you for your correction. We will fix it.

**Comment by tomohideshibata** [comment]
Thanks!
