### ISSUE TITLE
No answer in japanese_idiom

### ISSUE THREAD

**Issue by tomohideshibata** [nlp-waseda/JMMLU#6]
Thank you for publishing the great benchmark.

The answer to the following question "「言動が自在で角が立たず、物事をすらすら処理していくこと」という意味を持つ熟語は？" is "B: 因果応報", but I think this is not correct.
There seems to be no answer among the options, and one possible answer is "円転滑脱".
https://github.com/nlp-waseda/JMMLU/blob/main/JMMLU_NC_ND/japanese_idiom.csv#L74

Thank you.

**Comment by ZeekYin** [comment]
Thank you for your correction. We will fix it.

**Comment by tomohideshibata** [comment]
Thanks!
